---
# ------------------ Training configurations ------------------------
seed: 100               # seed to initialize random number generators

#------ optimizer
optimizer:
  name: Adam
  weight_decay: 0.00
  momentum: 0.9
  lr: 1e-3
  loss: l1l2 # l1, mse or rmse
  batch_size: 2
  epochs: 50
  load_model_loc: 0
  mu: 1e4
  lamb: 0.5

#----- configure the data loader
data:
  us_fac: 8
  us_fac_lambda: 8
  method: n2n_ssdu
  sample_type: columns
  train_trunc: 10000000
  val_trunc: 2000000
  nx: 640
  ny: 320
  nc: 20
  fully_samp_size: 10
  poly_order: 8
  sigma1: 4e-2
  sigma2: 2e-2

#----- network params
network:
  device: cuda     # uses cpu if gpu not available
  type: varnet
  ncascades: 5
  denoi_model: unet
  nlayers_dncnn: 18
