
#----- configure the data loader
data:
  set: fastmri
  nx: 640
  ny: 320
  train_trunc: null
  val_trunc: null
  fixed_ncoil: 16
  norm: True

#---- sampling and further sampling (lambda) masks
mask:
  sample_type: columns
  sample_type_lambda: columns
  fully_samp_size: 10
  fully_samp_size_lambda: 10
  poly_order: 8
  poly_order_lambda: 8
  us_fac: 8
  us_fac_lambda: 2
  fixed_omega: True

#----- measurement and additional noise
noise:
  sim_noise: True
  sigma1: 0.06
  alpha: 1
  whiten: False
  whiten_sq_sz: 30

#----- network params
network:
  type: varnet
  denoi_model: split_unet
  ncascades: 5

#------ optimizer
optimizer:
  method: robust_ssdu
  K_weight: true
  alpha_weight: true
  batch_size: 2
  epochs: 100
  noise2recon_lamb: 1
  load_model_root: null
  loss: mse
  lr: 1e-3
  momentum: 0.9
  name: Adam
  weight_decay: 0.0
  seed: 100
  sched_mstones: null

