
#----- configure the data loader
data:
  fully_samp_size: 10
  method: n2n_ssdu
  nc: 20
  nx: 640
  ny: 320
  poly_order: 8
  poly_order_lambda: 8
  sample_type: columns
  sigma1: 0.06
  sigma2: 0.06
  train_trunc: 10000000
  us_fac: 8
  us_fac_lambda: 2
  val_trunc: 2000000
  set: fastmri
  sim_noise: True
  loc: auto

#----- network params
network:
  denoi_model: unet
  device: cuda
  ncascades: 5
  nlayers_dncnn: 1
  type: varnet

#------ optimizer
optimizer:
  K_weight: true
  alpha_weight: true
  batch_size: 2
  epochs: 1
  lamb: 0.5
  load_model_loc: 0
  loss: mse
  lr: 1e-3
  momentum: 0.9
  mu: 1e4
  name: Adam
  weight_decay: 0.0
  seed: 100
  sched_mstones: [1000]

hyp_tuning:
  lambda_active: False
  lambda_start: 10.0
  alpha_active: False
  alpha_start: 0.5
