---
# ------------------ Training configurations ------------------------
seed: 100               # seed to initialize random number generators

#------ optimizer
optimizer:
  K_weight: true
  alpha_weight: true
  name: Adam
  weight_decay: 0.00
  momentum: 0.9
  lr: 1e-3
  loss: mse # l1, mse or rmse
  batch_size: 2
  epochs: 100
  load_model_loc: 0
  mu: 1e4
  lamb: 0.5

#----- configure the data loader
data:
  us_fac: 8
  us_fac_lambda: 2
  method: ssdu
  sample_type: bern
  val_trunc: 2000000
  nx: 640
  ny: 320
  nc: 20
  fully_samp_size: 10
  poly_order: 8
  sigma1: 0.0000e-2
  sigma2: 0.0000e-2

#----- network params
network:
  device: cuda     # uses cpu if gpu not available
  type: varnet
  ncascades: 5
  denoi_model: unet_single
  nlayers_dncnn: 18


hyp_tuning:
  lambda_active: True
  lambda_start: 2.0
  alpha_active: False
  alpha_start: 0.5
